name: "whisper_small_fp16_decoder"

platform: "onnxruntime_onnx"

max_batch_size: 0

input {
  name: "input_ids"
  data_type: TYPE_INT64
  dims: [ -1, -1 ]
}

input {
  name: "encoder_hidden_states"
  data_type: TYPE_FP32
  dims: [ -1, -1, 768 ]
}

output {
  name: "logits"
  data_type: TYPE_FP32
  dims: [ -1, -1, 51865 ]
}

output {
  name: "present.0.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.0.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.0.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.0.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.1.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.1.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.1.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.1.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.2.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.2.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.2.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.2.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.3.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.3.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.3.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.3.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.4.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.4.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.4.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.4.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.5.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.5.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.5.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.5.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.6.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.6.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.6.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.6.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.7.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.7.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.7.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.7.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.8.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.8.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.8.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.8.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.9.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.9.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.9.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.9.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.10.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.10.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.10.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.10.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.11.decoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.11.decoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.11.encoder.key"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

output {
  name: "present.11.encoder.value"
  data_type: TYPE_FP32
  dims: [ -1, 12, -1, 64 ]
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

parameters {
  key: "default_model_filename"
  value: { string_value: "decoder_model.onnx" }
}
