name: "whisper_small_fp16_encoder"

platform: "onnxruntime_onnx"

max_batch_size: 0

input {
  name: "input_features"
  data_type: TYPE_FP32
  dims: [ -1, 80, 3000 ]
}

output {
  name: "last_hidden_state"
  data_type: TYPE_FP32
  dims: [ -1, 1500, 768 ]
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

parameters {
  key: "default_model_filename"
  value: { string_value: "encoder_model.onnx" }
}
