// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "**GET** — возвращает query-параметры JSON-объектом или ` + "`" + `{}` + "`" + `. **Остальные методы** (POST и др.) — возвращают тело запроса; при непустом теле повторяется исходный ` + "`" + `Content-Type` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Эхо запроса",
                "responses": {
                    "200": {
                        "description": "GET: ключи из query",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/transcribe": {
            "post": {
                "description": "Принимает аудиофайл в поле формы ` + "`" + `audio` + "`" + `, создаёт ` + "`" + `task_id` + "`" + ` (UUID) и ставит задачу в очередь. Формат: wav/mp3 и совместимые типы, поддерживаемые пайплайном.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Распознавание речи",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Аудиофайл (wav/mp3)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "task_id в теле JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Нет поля audio или неверная форма",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка чтения файла или записи в очередь",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает агрегированный статус сервисов (например, ` + "`" + `redis_status` + "`" + `). При недоступности Redis — HTTP 503.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка готовности",
                "responses": {
                    "200": {
                        "description": "Все проверки прошли",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Whisper Fiber API",
	Description:      "HTTP API для очереди распознавания аудио (Whisper) через Redis. Версионированные маршруты: `/api/v1/...`.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
